const MESSAGES: Record<string, string> = {
  badNickname: 'Pick a nickname of 1–16 characters.',
  roomNotFound: 'No room with that code. Check the code and try again.',
  roomFull: 'That room is full (3 players).',
  gameInProgress: 'That game has already started.',
  serverBusy: 'The server is full right now. Try again in a minute.',
  rateLimited: 'Slow down a little.',
  alreadyInRoom: 'You already have a seat in a room.',
  notHost: 'Only the host can do that.',
  notEnoughPlayers: 'You need at least 2 players to start.',
  sessionNotFound: 'Your seat expired while you were away. Join the room again to play.',
  staleVersion: 'The table changed. Try again.',
  timeout: 'The server did not answer. Check your connection.',
  notYourTurn: "It's not your turn.",
  noPlaysLeft: 'You have no plays left this turn.',
  insufficientPayment: 'Select enough to cover what you owe, or everything you have.',
  hotelFirst: 'Pay the Hotel before its House.',
  internal: 'Something went wrong on the server.',
  // Client-side refusals.
  offline: "You're offline. Wait until the connection is back.",
  busy: 'Still sending your last move.',
  noSession: 'You no longer have a seat in this room.',
  notPlaying: 'The game has not started yet.',
  // Room and request errors.
  badRequest: 'The server did not understand that request.',
  notFound: 'That page does not exist.',
  gameOver: 'The game is over.',
  notFinished: 'The game is not over yet.',
  unknownIntent: 'That move does not exist.',
  unknownPlayer: 'That player is not in this game.',
  // Rule errors; the table only offers legal moves, so these mostly follow a race with another player.
  wrongPhase: "You can't do that right now.",
  nothingPending: 'There is nothing to answer.',
  notAwaitingYou: 'Nobody is waiting on you.',
  targetRequired: 'Choose a player first.',
  invalidTarget: "You can't target that.",
  unknownCard: 'That card is not in this game.',
  unknownGroup: 'That set is no longer on the table.',
  cardNotInHand: 'That card is no longer in your hand.',
  cardNotOnTable: 'That card is no longer on the table.',
  wrongCard: "That card can't be played that way.",
  duplicateCard: 'The same card was picked twice.',
  notAProperty: 'That card is not a property.',
  propertyCannotBeBanked: "Properties can't go in the bank.",
  invalidColor: "That card can't be that color.",
  noPropertyOfColor: 'You have no properties of that color.',
  noOp: 'That card is already there.',
  groupFull: 'That set is already full.',
  groupNotComplete: 'Buildings go on a full set.',
  targetInCompleteSet: "You can't take a card from a full set.",
  ownCardInCompleteSet: "You can't trade away a card from your own full set.",
  targetNotComplete: 'Deal Breaker needs a full set.',
  notBuildable: "Railroads and utilities can't have buildings.",
  alreadyBuilt: 'That set already has that building.',
  noHouse: 'Build a House before a Hotel.',
  notPayable: "You can't pay with that card.",
  wrongDiscardCount: 'Discard exactly the number of cards shown.',
};

/** Human wording for a server or engine error code. */
export function errorMessage(code: string): string {
  return MESSAGES[code] ?? `That didn't work (${code}).`;
}
